<?php

namespace Players;

class ElhadryChild extends ElhadryFather
{
	public function Keeping()
	{
//		return parent::Keeping(); // TODO: Change the autogenerated stub
		//Wrong way
//		return true;
		//True way
		return "Child Good Keeping";
	}
}